/**
 * Reporting - Status reports, weekly digest, health dashboard
 *
 * Generates formatted reports for the gap closure program:
 * - Weekly comprehensive status report
 * - Workstream detail reports
 * - Health dashboard summary (for daily digest integration)
 */

import programState from './program-state.js';
import humanTasks from './human-tasks.js';
import escalation from './escalation.js';

let logger = () => {};

export function init(log) {
  logger = log || (() => {});
}

/**
 * Generate weekly comprehensive status report.
 */
export function generateWeeklyReport() {
  const health = programState.getProgramHealth();
  const overdue = programState.getOverdueMilestones();
  const blockers = programState.getAllBlockers();
  const taskSummary = humanTasks.getTaskSummary();
  const escalations = escalation.getEscalationSummary();
  const upcomingTasks = humanTasks.getTasksDueSoon(7);
  const dueSoonMs = programState.getMilestonesDueSoon(7);

  const date = new Date().toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  const lines = [
    `## :compass: Atlas Weekly Operations Report`,
    `*${date}*`,
    '',
    '---',
    '',
    '### Program Summary',
    `**Overall Progress:** ${health.overall.completedMilestones}/${health.overall.totalMilestones} milestones (${health.overall.progress}%)`,
    '',
  ];

  // Workstream health table
  lines.push('### Workstream Health');
  lines.push('| WS | Name | Progress | Completed | Overdue | Blocked | Health |');
  lines.push('|---|---|---|---|---|---|---|');

  for (const ws of health.workstreams) {
    const icon = ws.health === 'green' ? ':green_circle:' :
                 ws.health === 'yellow' ? ':yellow_circle:' : ':red_circle:';
    lines.push(`| ${ws.wsId} | ${ws.name} | ${ws.progress}% | ${ws.completed}/${ws.total} | ${ws.overdue} | ${ws.blocked} | ${icon} |`);
  }
  lines.push('');

  // Overdue milestones
  if (overdue.length > 0) {
    lines.push('### :warning: Overdue Milestones');
    for (const ms of overdue) {
      lines.push(`- **${ms.id}**: ${ms.title} *(${ms.wsName}, ${ms.weeksBehind}w behind, owner: ${ms.owner || 'unassigned'})*`);
    }
    lines.push('');
  }

  // Upcoming milestones (next 7 days)
  if (dueSoonMs.length > 0) {
    lines.push('### :calendar: Upcoming Milestones (Next 7 Days)');
    for (const ms of dueSoonMs) {
      lines.push(`- **${ms.id}**: ${ms.title} *(Week ${ms.week}, owner: ${ms.owner || 'unassigned'})*`);
    }
    lines.push('');
  }

  // Blockers
  if (blockers.length > 0) {
    lines.push('### :no_entry: Active Blockers');
    for (const b of blockers.slice(0, 8)) {
      if (b.type === 'dependency') {
        lines.push(`- :link: ${b.upstream.title} → ${b.downstream.title}`);
      } else {
        lines.push(`- ${b.milestoneTitle} *(${b.wsName})*${b.reason ? `: ${b.reason}` : ''}`);
      }
    }
    lines.push('');
  }

  // Human tasks
  lines.push('### :clipboard: Human Tasks');
  lines.push(`- **Open:** ${taskSummary.open} | **Overdue:** ${taskSummary.overdue} | **Completed:** ${taskSummary.completed}`);
  if (Object.keys(taskSummary.byAssignee).length > 0) {
    lines.push(`- **By owner:** ${Object.entries(taskSummary.byAssignee).map(([k, v]) => `${k}: ${v}`).join(', ')}`);
  }
  if (upcomingTasks.length > 0) {
    lines.push(`- **Due this week:**`);
    for (const t of upcomingTasks.slice(0, 5)) {
      lines.push(`  - ${t.title} *(${t.assignee}, due ${t.dueDate?.slice(0, 10)})*`);
    }
  }
  lines.push('');

  // Escalations
  if (escalations.total > 0) {
    lines.push('### :rotating_light: Escalations (Last 7 Days)');
    lines.push(`- Total: ${escalations.total} | Critical: ${escalations.critical} | Warnings: ${escalations.warnings}`);
    for (const e of escalations.items) {
      lines.push(`- [${e.severity}] ${e.message}`);
    }
    lines.push('');
  }

  // Recommendations
  lines.push('### Recommendations');
  const recs = generateRecommendations(health, overdue, blockers, taskSummary);
  for (const rec of recs) {
    lines.push(`- ${rec}`);
  }
  lines.push('');

  lines.push('---');
  lines.push('*Generated by Atlas Operations Nerve Center*');

  return lines.join('\n');
}

/**
 * Generate a brief program status for daily digest integration.
 */
export function generateDigestSection() {
  const health = programState.getProgramHealth();
  const overdue = programState.getOverdueMilestones();
  const taskSummary = humanTasks.getTaskSummary();

  if (health.overall.totalMilestones === 0) {
    return null; // No program data yet
  }

  const lines = [
    '### :compass: Gap Closure Program',
    `**Progress:** ${health.overall.progress}% (${health.overall.completedMilestones}/${health.overall.totalMilestones} milestones)`,
    '',
  ];

  // Red workstreams only
  const redWs = health.workstreams.filter(w => w.health === 'red');
  if (redWs.length > 0) {
    lines.push('**Attention needed:**');
    for (const ws of redWs) {
      lines.push(`- :red_circle: ${ws.name}: ${ws.overdue} overdue, ${ws.blocked} blocked`);
    }
    lines.push('');
  }

  // Overdue highlights
  if (overdue.length > 0) {
    lines.push(`:warning: ${overdue.length} overdue milestone(s)`);
  }

  // Task highlights
  if (taskSummary.overdue > 0) {
    lines.push(`:clipboard: ${taskSummary.overdue} overdue human task(s)`);
  }

  return lines.join('\n');
}

/**
 * Generate actionable recommendations based on current state.
 */
function generateRecommendations(health, overdue, blockers, taskSummary) {
  const recs = [];

  if (overdue.length > 3) {
    recs.push('Consider a program reset meeting to re-baseline milestone dates');
  }

  const blockedWs = health.workstreams.filter(w => w.blocked > 0);
  if (blockedWs.length > 0) {
    recs.push(`Unblock ${blockedWs.map(w => w.name).join(', ')} - blocked milestones are cascading`);
  }

  if (taskSummary.overdue > 2) {
    recs.push(`${taskSummary.overdue} human tasks overdue - schedule a standup to clear backlog`);
  }

  const depBlockers = blockers.filter(b => b.type === 'dependency');
  if (depBlockers.length > 0) {
    recs.push(`${depBlockers.length} cross-workstream dependencies blocking progress`);
  }

  // Check for workstreams with no progress
  const stalled = health.workstreams.filter(w => w.progress === 0 && w.total > 0);
  if (stalled.length > 0) {
    recs.push(`Workstreams not yet started: ${stalled.map(w => w.name).join(', ')}`);
  }

  if (recs.length === 0) {
    recs.push('Program on track - maintain current velocity');
  }

  return recs;
}

export default {
  init,
  generateWeeklyReport,
  generateDigestSection,
};
