name: Mirror to GitLab

on:
  push:
    branches: ['**']
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Push to GitLab
        env:
          GL_TOKEN: ${{ secrets.GITLAB_TOKEN }}
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          git push --prune "https://oauth2:${GL_TOKEN}@gitlab.com/hwillGIT/${REPO_NAME}.git" "+refs/remotes/origin/*:refs/heads/*" "+refs/tags/*:refs/tags/*"
